# scikit-image 
全称：scikit-image SciKit (toolkit for SciPy) 数字图像处理的包  
安装：`pip install scikit-image`  
block_reduce网络示例：https://programtalk.com/python-examples/skimage.measure.block_reduce/

In [7]:
import numpy as np
from skimage.measure import block_reduce

image1 = np.arange(4 * 6).reshape(4, 6)
out1 = block_reduce(image1, (2, 3))  # 不指定func默认sum
out2 = block_reduce(image1, (2, 3), func=np.mean)
out3 = block_reduce(image1, (2, 3), func=np.max)
out4 = block_reduce(image1, (2, 3), func=np.median)
print(image1)
print()
print(out1)
print()
print(out2)
print()
print(out3)
print()
print(out4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[ 24  42]
 [ 96 114]]

[[ 4.  7.]
 [16. 19.]]

[[ 8 11]
 [20 23]]

[[ 4.  7.]
 [16. 19.]]
